import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class TXALanguage extends ChangeNotifier {
  static final TXALanguage instance = TXALanguage._internal();
  TXALanguage._internal();

  static const String _keyLang = 'txa_lang_code';

  String _currentLanguage = 'vi';
  String get currentLanguage => _currentLanguage;

  static const Map<String, String> supportedLanguages = {
    'vi': 'Tiếng Việt',
    'en': 'English',
  };

  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'app_title': 'Army',
      'splash_subtitle': 'Locket Clone UI',
      'language_select_title': 'Chọn Ngôn Ngữ',
      'format_select_title': 'Cấu Hình Định Dạng',
      'continue': 'Tiếp tục',
      'save': 'Lưu cấu hình',
      'cancel': 'Hủy',
      'accept_all': 'Chấp nhận tất cả',
      'reject_all': 'Từ chối tất cả',
      'feature_coming_soon': 'Chức năng đang được phát triển',
      'self_friend_blocked': 'Bạn không thể gửi lời mời kết bạn cho chính mình!',
      'add_friend': 'Thêm bạn bè',
      'add_friend_hint': 'Nhập đúng username của người bạn muốn kết bạn',
      'send_invite': 'Gửi lời mời',
      'friend_added': 'Đã chấp nhận lời mời từ %user%',
      'zoom_rear_only': 'Tính năng zoom chỉ hỗ trợ trên camera sau',
      'just_now': 'Ngay bây giờ',
      'mins_ago': 'phút trước',
      'hours_ago': 'giờ trước',
      'days_ago': 'ngày trước',
      'offline': 'Ngoại tuyến',
      'online': 'Trực tuyến',
      'show_timestamp': 'Hiển thị mốc thời gian (Timestamp)',
      'friends_count': '%count% người bạn',
      'rollcall_title': 'Rollcall - Ngay bây giờ',
      'select_photo': 'CHỌN ẢNH',
      'history_label': 'Lịch sử',
      'double_tap': 'Double Tap',
      'add_new_friend': 'Thêm một người bạn mới',
      'search_friend_placeholder': 'Nhập tên hoặc username (ví dụ: @tienndaii19)',
      'invites_title': 'Lời mời',
      'friends_title': 'Bạn bè',
      'accept': 'Chấp nhận',
      'decline': 'Từ chối',
      'cancel_request': 'Hủy yêu cầu',
      'best_friend': 'Bạn thân',
      'love_invite_sent': 'Đã gửi lời mời yêu',
      'single_camera_found': 'Chỉ tìm thấy 1 camera trên thiết bị',
      'photo_captured': '📸 Đã chụp ảnh Locket!',
      'camera_viewfinder': 'Khung ảnh Army',
      'history_photos_title': 'Lịch sử ảnh',
      'photo_item': 'Ảnh',
      'change_language': 'Đổi ngôn ngữ',
      'settings': 'Cài đặt',
      'send_to': 'Gửi đến...',
      'add_message_caption': 'Thêm một tin nhắn...',
      'all_friends': 'Tất cả',
      'photo_saved': '💾 Đã lưu ảnh vào thư viện!',
      'photo_sent': '🚀 Đã gửi Locket thành công!',
      'crop_image_title': 'Cắt ảnh Locket',
      'crop_image_hint': 'Kéo để di chuyển, dùng 2 ngón tay hoặc thanh trượt để phóng to/thu nhỏ ảnh.',
      'crop_save': 'Cắt & Dùng ảnh',
      'zoom_image': 'Thu phóng',
      'cropping_image': 'Đang xử lý cắt ảnh...',
      'permission_title': 'Yêu cầu quyền ứng dụng',
      'permission_desc': 'Army cần quyền truy cập Camera, Thư viện ảnh và Thông báo để chụp & gửi Locket cho bạn bè.',
      'permission_grant': 'Cấp quyền ứng dụng',
      'permission_granted_toast': '✅ Đã cấp quyền ứng dụng thành công!',
      'noti_reaction_title': '❤️ Cảm xúc mới',
      'noti_reaction_body': '%sender% vừa thả cảm xúc vào ảnh Locket của bạn!',
      'noti_message_title': '💬 Tin nhắn mới',
      'noti_message_body': '%sender%: %content%',
      'noti_reply_title': '💬 Phản hồi Feed',
      'noti_reply_body': '%sender% vừa trả lời bức ảnh của bạn!',
      'noti_morning_title': '☀️ Chào buổi sáng cùng Locket!',
      'noti_morning_body': 'Đừng quên lưu lại khoảnh khắc buổi sáng cùng bạn bè nhé!',
      'noti_evening_title': '⏰ Dí deadline Rollcall cuối ngày!',
      'noti_evening_body': 'Đã đến giờ gửi ảnh Locket cho hội bạn thân rồi!',
      'aspect_ratio': 'Tỷ Lệ Khung Ảnh Locket',
      'aspect_1_1': '1:1 Vuông (Chuẩn Locket 🔳)',
      'aspect_4_3': '4:3 Hình Chữ Nhật (Mở Rộng 📱)',
      'format_unit': 'Đơn Vị Dung Lượng',
      'time_format': 'Định Dạng Mốc Thời Gian',
      'activity_format': 'Định Dạng Hoạt Động',
      'login_title': 'Đăng Nhập Army',
      'login_subtitle': 'Đăng nhập để lưu giữ & chia sẻ Locket với bạn bè',
      'email_or_username': 'Email hoặc Username',
      'password': 'Mật khẩu',
      'login_btn': 'Đăng Nhập',
      'google_login_btn': 'Đăng nhập với Google',
      'no_account': 'Chưa có tài khoản?',
      'create_new_account': 'Tạo tài khoản mới',
      'register_title': 'Tạo Tài Khoản Army',
      'select_avatar_title': 'Chọn Avatar Đại Diện (10 Mẫu Preset)',
      'email_domain_hint': 'ví dụ: user@gmail.com, icloud.com...',
      'dob_title': 'Ngày Tháng Năm Sinh (DOB)',
      'dob_hint': 'Chọn ngày sinh (DD/MM/YYYY)',
      'confirm_password': 'Xác Nhận Mật Khẩu',
      'register_btn': 'Đăng Ký Tài Khoản',
      'bad_word_error': '🚫 Caption chứa từ ngữ không phù hợp ("%word%")! Vui lòng chỉnh sửa lại.',
      'google_login_success': '🌐 Đăng nhập Google thành công! Chào mừng %user%',
      'login_success': '👋 Đăng nhập thành công! Chào mừng %user%',
      'register_success': '🎉 Đăng ký thành công! Đã tự động đăng nhập vào %user%',
      'gms_warning_title': '⚠️ Cảnh Báo Dịch Vụ Google Play',
      'gms_warning_desc': 'Thiết bị của bạn không có hoặc chưa bật Dịch vụ Google Play. Các tính năng như Đăng nhập bằng Google và Vị trí GPS sẽ bị tự động vô hiệu hóa.',
      'gms_warning_btn': 'Đã hiểu & Tiếp tục',
      'gms_disabled_tooltip': 'Dịch vụ Google Play không khả dụng trên thiết bị này',
      'camera_error_title': 'Lỗi Khởi Tạo Camera',
      'camera_retry_btn': 'Thử Lại Khởi Tạo',
      'camera_in_use_error': 'Thiết bị camera bận hoặc đang được ứng dụng khác sử dụng. Bấm thử lại để giải phóng.',
      'no_camera_found': 'Không tìm thấy thiết bị camera trên hệ thống',
      'private_only': 'Chỉ mình tôi',
      'camera_access_denied': 'Quyền truy cập Camera bị từ chối. Vui lòng cấp quyền trong Cài đặt.',
      'lover': 'Người yêu 💖',
      'private': 'Riêng tư',
      'public': 'Công khai',
      'voice_recording_done': '🎙️ Đã ghi âm xong voice (%sec%s)!',
      'voice_recording_in_progress': 'Đang ghi âm (%sec%s)... Tắt',
      'voice_attached': '🎵 Đã đính kèm Voice (15s)',
      'add_voice': 'Thêm voice (15s)',
      'get_gms_location': '📍 Cấp quyền & Lấy vị trí',
      'getting_gms_location': '📡 Đang lấy vị trí...',
      'gms_location_fetched_toast': '📍 Đã lấy đúng vị trí: %location%',
      'location_permission_granted': '✅ Đã cấp quyền vị trí thành công!',
      'location_caption_grey': 'Vị trí',
      'refetch_location': 'Cập nhật lại vị trí',
      'mood_selected': 'Tâm trạng: %emoji%',
      'reaction_sent': '%emoji% Đã thả cảm xúc!',
      'message_sent_to': '💬 Đã gửi tin nhắn đến %user%!',
      'post_options_of': 'Tùy chọn bài viết của %user%',
      'save_image_device': 'Lưu ảnh về thiết bị',
      'image_saved_success': '💾 Đã lưu ảnh thành công!',
      'report_post': 'Báo cáo bài viết',
      'report_sent_success': '🚩 Đã gửi báo cáo bài viết!',
      'delete_post_this': 'Xóa bài viết này',
      'post_deleted_success': '🗑️ Đã xóa bài viết!',
      'no_posts_yet': 'Chưa có bài đăng nào!',
      'type_message_hint': 'Gửi tin nhắn...',
      'replying_to': 'Đang trả lời %user%',
      'replying_to_self': 'Đang trả lời chính mình',
      'reply_label': 'Trả lời',
      'copy_label': 'Sao chép',
      'message_copied_toast': '📋 Đã sao chép tin nhắn!',
      'friend_reacted_message': '%sender% đã thả cảm xúc vào tin nhắn',
      'memory_title': 'Tên kỷ niệm',
      'memory_hint': 'VD: Chuyến đi Đà Lạt...',
      'use_default': 'Dùng mặc định',
      'memory_saved': 'Đã lưu tên kỷ niệm!',
      'upload_error': '❌ Lỗi khi tải ảnh lên: %error%',
      'email_invalid_domain': 'Vui lòng nhập Email thuộc Gmail, iCloud hoặc Microsoft (Outlook, Hotmail)!',
      'confirm_password_mismatch': 'Mật khẩu xác nhận không trùng khớp!',
      'register_failed': 'Đăng ký thất bại!',
      'login_failed': 'Đăng nhập thất bại!',
      'google_login_failed': 'Đăng nhập Google thất bại!',
      'email_address_label': 'Địa Chỉ Email',
      'display_name_label': 'Tên Hiển Thị',
      'display_name_hint': 'Nhập tên hiển thị của bạn',
      'username_label': 'Username',
      'username_hint': 'ví dụ: @hoangnam872',
      'username_desc': 'Username dùng để kết bạn và tạo link chia sẻ profile riêng của bạn.',
      'password_min_hint': 'Tối thiểu 6 ký tự',
      'confirm_password_hint': 'Nhập lại mật khẩu phía trên',
      'author_reactions_title': 'Cảm xúc trên bài viết',
      'no_reactions_yet': 'Chưa có cảm xúc nào',
      'reactions_count': '%count% cảm xúc',
      'play_voice': 'Phát Voice (%sec%s)',
      'pause_voice': 'Tạm dừng Voice',
      'voice_recorded_preview': '🎙️ Đã ghi âm Voice (%sec%s)',
      'share_link_copied': '🔗 Đã sao chép liên kết chia sẻ!',
      'friends_badge': 'Bạn bè',
      'copy_invite_link_success': '📋 Đã sao chép liên kết lời mời: %link%',
      'edit_avatar_title': 'Đổi ảnh đại diện',
      'avatar_emoji_changed': 'Đổi avatar thành công!',
      'posts_badge': 'Army',
      'streak_days': 'ngày',
      'feed_display_mode': 'Hiển thị Feed Grid',
      'thought_bubbles': 'Bong bóng suy nghĩ',
      'photos_only': 'Hình ảnh',
      'choose_feed_mode_title': 'Chọn chế độ hiển thị Feed Grid',
      'widget_data_source': 'Nguồn dữ liệu Widget',
      'widget_size': 'Kích cỡ Widget',
      'block_user': 'Chặn',
      'download_photo': 'Tải ảnh xuống',
      'filter_everyone': 'Mọi người',
      'filter_best_friends': 'Bạn thân',
      'filter_friends': 'Bạn',
      'share_profile': 'Chia sẻ',
      'streak_label': 'Nhịp',
      'camera_theme_title': 'Chọn chủ đề camera',
      'camera_theme_subtitle': 'Thay đổi màu nền và viền camera',
      'change_app_icon': 'Thay đổi icon ứng dụng',
      'settings_title': 'Cài đặt',
      'language_settings': 'Ngôn ngữ',
      'share_post': 'Chia sẻ bài viết',
      'logout': 'Đăng xuất',
      'logout_confirm_title': 'Đăng xuất?',
      'add_friend_to_chat_hint': 'Kết bạn để nhắn tin!',
      'report_title': 'Báo cáo',
      'block_title': 'Chặn',
      'start_conversation_title': 'Bắt đầu cuộc hội thoại!',
      'start_conversation_desc': 'Trả lời một tâm trạng của họ để bắt đầu cuộc hội thoại',
      'blocked_user_success': 'Đã chặn %user%!',
      'logout_confirm_msg': 'Bạn có chắc muốn đăng xuất khỏi tài khoản này không?',
      'logout_confirm_btn': 'Đăng xuất',
      'search_start_hint': 'Nhập tên hoặc username để tìm...',
      'friendship_me': 'Bạn',
      'friendship_friends': 'Bạn bè',
      'friendship_pending': 'Đang chờ',
      'friendship_add': 'Kết bạn',
      'friend_options_title': 'Tùy chọn bạn bè',
      'remove_best_friend': 'Bỏ khỏi bạn thân',
      'add_best_friend': 'Thêm vào bạn thân',
      'remove_friend': 'Xóa bạn bè',
      'remove_friend_confirm_title': 'Xóa %user%?',
      'remove_friend_confirm_desc': 'Bạn sẽ không còn thấy khoảnh khắc của nhau nữa.',
      'block_confirm_title': 'Chặn %user%?',
      'block_confirm_desc': 'Bạn sẽ không thể gửi tin nhắn hoặc xem khoảnh khắc của nhau nữa.',
      'my_username_label': 'Username của bạn',
      'username_copied': 'Đã sao chép username: %user%',
      'account_created_at': 'Đã tạo: %date%',
      'streak_active_msg': 'Chuỗi thắp lửa Streak 🔥: %count% ngày!',
      'streak_countdown': 'Còn %time% để rep/nối chuỗi 🔥',
      'streak_below_3_msg': 'Chuỗi Streak 🔥: %count% ngày',
      'profile_settings_tooltip': 'Trang cá nhân & Cài đặt (%user%)',
      'friends_list_tooltip': 'Danh sách bạn bè (%count% người)',
      'chat_messages_tooltip': 'Trò chuyện & Tin nhắn',
      'gallery_tooltip': 'Tải ảnh từ thư viện (Phím G)',
      'shutter_tooltip': 'Chụp ảnh Locket (Phím Space)',
      'flip_camera_tooltip': 'Đổi ống kính Camera (Phím C)',
      'feed_trigger_tooltip': 'Bảng tin & Lịch sử bài đăng (Mũi Tên Dưới / PageDown / Cuộn chuột)',
      'flash_off_tooltip': 'Tắt Flash',
      'flash_on_tooltip': 'Luôn Bật (Đèn pin)',
      'flash_auto_tooltip': 'Tự Động (Chớp khi chụp)',
      'flash_off_toast': '⚡ Tắt Flash',
      'flash_on_toast': '🔦 Luôn Bật (Đèn Pin)',
      'flash_auto_toast': '⚡ Tự Động khi chụp',
      'zoom_tooltip': 'Thu phóng camera',
      'zoom_preset_toast': '🔍 Thu phóng camera: %zoom%x',
      'loading_friends_list': 'Đang tải danh sách bạn bè...',
      'no_friends_yet': 'Chưa có bạn bè nào',
      'no_internet_title': 'Không Có Kết Nối Mạng',
      'no_internet_desc': 'Vui lòng kết nối Internet để sử dụng ứng dụng.',
      'exit_app_btn': 'Thoát Ứng Dụng',
      'press_back_again_to_exit': 'Nhấn back một lần nữa để thoát ứng dụng',
      'battery_critical_title': 'Cảnh Báo Pin Yếu 🔋',
      'battery_critical_desc': 'Mức pin hiện tại của thiết bị quá thấp (<= 5%). Vui lòng cắm sạc để tiếp tục sử dụng ứng dụng.',
      'connection_lost_toast': 'Mất kết nối Internet! Ứng dụng sẽ tự động đóng sau %sec% giây...',
      'connection_restored_toast': 'Đã kết nối Internet trở lại! Đang đồng bộ...',
      'countdown_exit_msg': 'Mất kết nối mạng! Ứng dụng tự đóng sau:',
      'close_settings': 'Đóng Cài Đặt',
      'close_btn': 'Đóng',
      'admin_panel_title': 'QUẢN TRỊ HỆ THỐNG',
      'admin_stats_tab': 'Thống kê & BXH',
      'admin_stats_overview': '📊 THỐNG KÊ TỔNG QUAN HỆ THỐNG',
      'admin_total_army': 'TỔNG ARMY (BÀI ĐĂNG)',
      'admin_total_users': 'TỔNG NGƯỜI DÙNG',
      'admin_total_couples': 'CẶP ĐÔI KẾT ĐÔI',
      'admin_total_interactions': 'LƯỢT TƯƠNG TÁC',
      'admin_today_posts': '+%count% hôm nay 🔥',
      'admin_today_users': '+%count% mới hôm nay ⚡',
      'admin_couples_sub': 'Đang song hành ❤️',
      'admin_interactions_sub': 'Reactions & Tim',
      'admin_top_streak_title': '🏆 TOP CHUỖI NGỌN LỬA CAO NHẤT HỆ THỐNG',
      'admin_top_posters_title': '📸 TOP NGƯỜI DÙNG ĐĂNG BÀI NHIỀU NHẤT',
      'admin_days_unit': 'ngày',
      'admin_posts_unit': 'bài',
      'admin_delete_user_title': 'Xóa người dùng',
      'admin_delete_user_confirm': 'Bạn có chắc chắn muốn xóa tài khoản %user% không?',
      'admin_delete_post_title': 'Xóa bài đăng',
      'admin_delete_post_confirm': 'Bạn có chắc muốn xóa bài đăng này không?',
      'admin_panel_subtitle': 'Quản trị Users, Posts và Reports',
      'admin_delete_btn': 'Xóa',
      'admin_deleted_user_success': '🗑️ Đã xóa người dùng %user%!',
      'admin_resolve_report_success': '✅ Báo cáo đã được xử lý và gửi thông báo cho %reporter%',
      'admin_no_users': 'Không có người dùng nào',
      'admin_role_created': 'Quyền: %role% | Tạo: %date%',
      'admin_you': 'Bạn',
      'admin_unfriend_tooltip': 'Hủy kết bạn',
      'admin_friend_tooltip': 'Kết bạn',
      'admin_unfriend_success': '💔 Đã hủy kết bạn với %user%',
      'admin_friend_success': '🤝 Đã kết bạn với %user%',
      'admin_no_posts': 'Không có bài viết nào',
      'admin_no_caption': 'Không có caption',
      'admin_deleted_post_success': '🗑️ Đã xóa bài đăng!',
      'admin_no_reports': 'Không có báo cáo nào',
      'admin_report_by': 'Báo cáo bởi: %reporter%',
      'admin_report_resolved': 'ĐÃ XỬ LÝ',
      'admin_report_pending': 'ĐANG CHỜ',
      'admin_report_target': 'Đối tượng: %target%',
      'admin_report_content': 'Nội dung: "%content%"',
      'admin_resolve_fcm_btn': 'Giải quyết & Gửi FCM',
      'admin_reporter_notified': 'Đã gửi thông báo cho reporter',
      'admin_refresh_tooltip': 'Tải lại dữ liệu',
      'unfriend_success': 'Đã xóa kết bạn với %user%',
      'cannot_drag_normal_above_priority': 'Không thể kéo bạn bình thường lên trên Bạn thân hoặc Người yêu!',
      'cannot_drag_best_below_priority': 'Bạn thân phải luôn nằm ở vị trí đầu danh sách!',
      'cannot_drag_lover_above_best': 'Không thể kéo Người yêu lên trên Bạn thân!',
      'cannot_drag_lover_below_normal': 'Người yêu phải luôn nằm trên bạn bè bình thường!',
      'friend_order_updated': 'Đã cập nhật thứ tự bạn bè!',
      'sent_invites': 'Lời mời đã gửi',
      'pending_acceptance': 'Đang chờ đối phương chấp nhận...',
      'request_cancelled': 'Đã hủy yêu cầu kết bạn!',
      'streak_sheet_title': 'Nhịp Army hằng ngày',
      'streak_current_days': 'Nhịp hiện tại: %count% ngày',
      'streak_keep_subtitle': 'Bắt đầu giữ nhịp Army bằng cách gửi 1 khoảnh khắc hôm nay!',
      'streak_milestones_title': 'Dấu mốc Army',
      'streak_next_title': 'Mốc tiếp theo',
      'streak_add_days_hint': 'Thêm %count% ngày để mở mốc %name%',
      'streak_restore_btn': 'Khôi phục chuỗi',
      'streak_countdown_tooltip': 'Còn %time% để khôi phục/duy trì chuỗi rep nhịp...',
      'streak_current_badge': 'Hiện tại',
      'streak_unlocked_badge': 'Đã mở',
      'streak_m_3': 'Mầm Kiến',
      'streak_m_7': 'Kiến Lính',
      'streak_m_14': 'Kiến Thợ',
      'streak_m_30': 'Tổ Kiến',
      'streak_m_45': 'Kiến Vàng',
      'streak_m_60': 'Chiến Sĩ',
      'streak_m_75': 'Tướng Kiến',
      'streak_m_90': 'Nữ Hoàng',
      'coachmark_completed': '🎉 Bạn đã hoàn thành hướng dẫn Armi! Chúc bạn trải nghiệm Army thật vui!',
      'replay_coachmark': 'Xem lại hướng dẫn Armi 🐜',
      'coachmark_step_1': 'Chào bạn! Mình là Armi 🐜. Đây là Avatar và trang Profile cá nhân của bạn!',
      'coachmark_step_2': 'Bấm vào đây để xem danh sách Bạn bè và các Lời mời kết bạn đang chờ nha!',
      'coachmark_step_3': 'Bấm nút camera ở giữa để chụp khoảnh khắc Locket và chia sẻ ngay cho bạn bè!',
      'replied_to_post': 'Đã trả lời bài đăng',
      'email_in_use_error': 'Email này đã được sử dụng!',
      'username_exists_error': 'Username này đã tồn tại!',
      'incorrect_password_error': 'Mật khẩu nhập vào không chính xác!',
      'account_not_found_error': 'Tài khoản với Email hoặc Username này không tồn tại!',
      'google_auth_failed': 'Xác thực Google thất bại!',
      'google_account_error': 'Không thể xác thực thông tin tài khoản Google!',
      'google_login_cancelled': 'Hủy đăng nhập Google!',
      'holiday_30_4_1_5': 'Chào mừng Ngày Giải phóng miền Nam 30/4 & Quốc tế Lao động 1/5!',
      'holiday_2_9': 'Mừng Ngày Quốc Khánh Nước Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam 2/9!',
      'holiday_20_11': 'Tri ân Ngày Nhà Giáo Việt Nam 20/11! 💐',
      'tet_countdown_days': 'Còn %days% ngày nữa đến Tết %name% 🧧',
      'tet_new_year': '🧧 Chúc Mừng Năm Mới %name%! Vạn Sự Như Ý! 🌸',
      'tet_default': 'Tết %name% 🧧',
      'blur_overlay_enabled': 'Đã bật ẩn bài đăng! 👁️',
      'blur_overlay_disabled': 'Đã tắt ẩn bài đăng! 👁️',
      'tet_wish_1': 'Vạn sự như ý! 🧧',
      'tet_wish_2': 'An khang thịnh vượng! 🌸',
      'tet_wish_3': 'Tấn tài tấn lộc! 🍊',
      'tet_wish_4': 'Tài lộc đầy nhà! 💰',
      'tet_wish_5': 'Sức khỏe dồi dào! 💪',
      'tet_wish_6': 'Cười tươi như hoa! 😄',
      'tet_wish_7': 'Tỷ sự như mơ! ✨',
      'tet_wish_8': 'Mọi điều suôn sẻ! 🎈',
      'tet_wish_9': 'Quả Tết của %user% đây! 🧧',
      'tet_wish_10': 'Tết %name% của %user% đây! 🌸',
      'tet_wish_11': 'Lì xì cho %user% đi nào! 🧧',
      'tet_wish_12': 'Năm mới của %user% vạn sự như ý! 😄',
      'zodiac_aries': '♈ Bạch Dương %user% tràn đầy năng lượng!',
      'zodiac_taurus': '♉ Kim Ngưu %user% kiên định & đáng tin cậy!',
      'zodiac_gemini': '♊ Song Tử %user% thông minh, nhạy bén!',
      'zodiac_cancer': '♋ Cự Giải %user% tình cảm & ấm áp!',
      'zodiac_leo': '♌ Sư Tử %user% tự tin & tỏa sáng!',
      'zodiac_virgo': '♍ Xử Nữ %user% tỉ mỉ & tinh tế!',
      'zodiac_libra': '♎ Thiên Bình %user% yêu hòa bình, cân bằng!',
      'zodiac_scorpio': '♏ Thiên Yết %user% bí ẩn & cuốn hút!',
      'zodiac_sagittarius': '♐ Nhân Mã %user% tự do & phóng khoáng!',
      'zodiac_capricorn': '♑ Ma Kết %user% trách nhiệm & kiên trì!',
      'zodiac_aquarius': '♒ Bảo Bình %user% sáng tạo, độc bản!',
      'zodiac_pisces': '♓ Song Ngư %user% mơ mộng & tốt bụng!',
      'love_menu_title': 'Chế độ Cặp đôi',
      'set_love_date': 'Chọn ngày bắt đầu yêu',
      'send_love_invite_btn': 'Gửi lời mời yêu',
      'love_invitation_title': 'Lời mời kết đôi tình yêu 💖',
      'love_invitation_desc': '%user% muốn kết đôi và cùng bạn lưu giữ những khoảnh khắc yêu thương bắt đầu từ %date%.',
      'anniversary_days': '%days% Ngày bên nhau',
      'break_up_confirm_title': 'Hủy kết đôi?',
      'break_up_confirm_desc': 'Bạn và đối phương sẽ không còn chung Love Feed và đếm ngày yêu nữa.',
      'break_up_btn': 'Hủy kết đôi',
      'love_feed_title': 'Love Feed 💖',
      'empty_love_feed': 'Chưa có bài đăng tình yêu nào! Hãy chụp khoảnh khắc gửi cho đối phương nhé.',
      'status_bubble_hint': 'Bạn đang nghĩ gì?',
      'love_invite_pending_error': 'Bạn hoặc đối phương đang có lời mời yêu khác chờ xử lý!',
      'waiting_response': 'Đang chờ phản hồi...',
      'love_setup_waiting_desc': 'Lời mời kết đôi của bạn đã được gửi đến %user%. Chờ người ấy chấp nhận để bắt đầu đếm ngày yêu nhé!',
      'revoke_invite_btn': 'Thu hồi lời mời',
      'revoke_invite_success': 'Đã thu hồi lời mời kết đôi.',
      'select_friend_to_couple': 'Vui lòng chọn một người bạn để kết đôi!',
      'love_invite_sent_success': 'Đã gửi lời mời yêu!',
      'mic_permission_denied': '⚠️ Quyền Micro chưa được cấp!',
      'loading_profile_data': 'Đang tải dữ liệu...',
      'army_building_timeline': 'Army đang dựng timeline...',
      'love_couple_success_toast': '💖 Chúc mừng! Hai bạn đã chính thức kết đôi thành công!',
      'love_couple_declined_toast': 'Đã từ chối lời mời kết đôi.',
      'break_up_success_toast': '💔 Đã hủy kết đôi thành công.',
      'break_up_failed_toast': 'Lỗi hủy kết đôi!',
      'love_status_updated_toast': 'Đã cập nhật trạng thái mới!',
      'love_status_hint': 'Nhập tâm trạng (ví dụ: "anh ơi em đói")',
      'love_cannot_couple_self': 'Không thể tự kết đôi với chính mình',
      'love_you_already_coupled': 'Bạn đã có người yêu hoặc đang kết đôi!',
      'love_you_have_pending': 'Bạn đang có lời mời yêu ở trạng thái chờ. Hãy giải quyết trước khi gửi lời mời mới!',
      'love_user_not_found': 'Không tìm thấy người dùng "%user%"',
      'love_user_already_coupled': '%user% đã có người yêu rồi!',
      'love_user_has_pending': '%user% đang có lời mời yêu chờ xử lý với người khác!',
      'not_logged_in_error': 'Chưa đăng nhập',
      'love_invite_sent_success_to': 'Đã gửi lời mời yêu đến %user%',
      'love_invite_send_error': 'Lỗi gửi lời mời: %error%',
      'love_accept_error': 'Lỗi chấp nhận lời mời: %error%',
      'break_up_error_toast': 'Lỗi hủy kết đôi: %error%',
      'cannot_friend_self': 'Không thể kết bạn với chính mình',
      'friend_not_found': 'Không tìm thấy người dùng "%user%"',
      'already_friends': 'Đã là bạn bè rồi',
      'friend_request_already_sent': 'Đã gửi lời mời rồi',
      'friend_request_sent_to': 'Đã gửi lời mời đến %user%',
      'google_login_error': 'Lỗi Đăng Nhập Google: %error%',
      'love_status_coupled': 'Đang kết đôi với bạn 💖',
      'love_status_pending_received': 'Đã gửi cho bạn lời mời kết đôi! 📬',
      'love_days_together_label': 'Ngày bên nhau',
      'anniversary_date_label': 'Ngày kỷ niệm: %date%',
      'recap_button_title': 'Tóm tắt Khoảnh khắc 🌟',
      'recap_screen_title': 'Recap Khoảnh khắc',
      'recap_weekly': 'Tóm tắt Tuần',
      'recap_monthly': 'Tóm tắt Tháng',
      'recap_select_period': 'Chọn khoảng thời gian tóm tắt',
      'recap_no_posts': 'Không có khoảnh khắc nào trong khoảng thời gian này!',
      'recap_posts_sent': 'Bạn đã chia sẻ %count% khoảnh khắc!',
      'recap_active_days': 'Số ngày hoạt động: %days% ngày',
      'recap_with_lover': 'Bạn và %lover% đã trao đổi %count% khoảnh khắc!',
      'recap_with_friends': 'Bạn đã chia sẻ khoảnh khắc với %count% bạn bè!',
      'recap_top_mood': 'Tâm trạng/Emoji nổi bật của bạn',
      'recap_top_caption': 'Dòng trạng thái ấn tượng nhất',
      'recap_memories': 'KỶ NIỆM 📸',
      'recap_together': 'GẮN KẾT 🤝',
      'recap_weekly_desc': '7 ngày khoảnh khắc',
      'recap_monthly_desc': '30 ngày khoảnh khắc',
      'recap_default_weekly_caption': 'Một tuần tuyệt vời!',
      'recap_default_monthly_caption': 'Một tháng đáng nhớ!',
      'rollcall_join': 'Tham gia Rollcall để xem ảnh của bạn bè! 🔒',
      'rollcall_btn_join': 'Chụp ngay 📸',
      'rollcall_prompt_label': 'Thử thách Rollcall 📣',
      'rollcall_responses_title': 'Phản hồi Rollcall',
      'rollcall_no_responses': 'Chưa có ai tham gia Rollcall hôm nay!',
      'rollcall_activated': 'Đã kích hoạt chế độ Rollcall! 📣',
      'report_resolved_title': 'Báo cáo đã xử lý',
      'report_resolved_body': 'Báo cáo của bạn đã được xử lý nha.',
      'no_reactions_summary': 'Chưa có ai thả cảm xúc',
      'reactions_summary_count': '%count% người đã thả cảm xúc',
      'reacted_status': 'Đã thả cảm xúc',
      'recap_daily': 'Recap Ngày',
      'recap_daily_desc': 'Hôm nay của bạn',
      'recap_yearly': 'Recap Năm',
      'recap_yearly_desc': 'Kỷ niệm 365 ngày qua',
      'recap_all_time': 'Recap Trọn Đời',
      'recap_all_time_desc': 'Tất cả khoảnh khắc từ trước đến nay',
      'recap_stat_first_post': 'Bài đầu tiên:',
      'recap_stat_most_active': 'Hoạt động nhất:',
      'recap_stat_reactions_received': 'Cảm xúc nhận:',
      'recap_active_morning': 'Buổi sáng 🌅 (04:00 - 11:00)',
      'recap_active_afternoon': 'Buổi chiều ☀️ (11:00 - 17:00)',
      'recap_active_evening': 'Buổi tối 🌆 (17:00 - 22:00)',
      'recap_active_night': 'Ban đêm 🌌 (22:00 - 04:00)',
      'recap_default_daily_caption': 'Một ngày đầy ắp kỷ niệm!',
      'recap_default_custom_caption': 'Một giai đoạn tuyệt vời!',
      'achievements_title': 'Thành Tựu Army 🏆',
      'achievements_subtitle': 'Chinh phục cột mốc & nhận huy hiệu độc quyền',
      'achievement_unlocked': 'Đã Đạt',
      'achievement_locked': 'Chưa Đạt',
      'unlock_condition': 'Điều kiện giải khóa',
      'current_progress': 'Tiến độ hiện tại',
      'max_tier_reached': 'Đã đạt mốc Tối đa 💎',
      'tier_label': 'Mốc %tier%/%max% • %name%',
      'next_tier_target': 'Mốc tiếp theo: %target%',
      'roadmap_title': 'Lộ trình danh hiệu',
      'achievements_header_count': '🏆 %unlocked% / %total% Mốc Danh Hiệu',
      'target_label': 'Mục tiêu: %target%',
      'cat_all': 'Tất cả',
      'cat_posts': 'Khoảnh khắc 📸',
      'cat_friends': 'Bạn bè 🤝',
      'cat_streak': 'Streak 🔥',
      'cat_love': 'Cặp đôi 💖',
      'cat_stamps': 'Tem thư 📮',
      'cat_spotify': 'Âm nhạc 🎵',
      'cat_ultimate': 'Đỉnh Cao 🌟',
      'diff_easy': 'Dễ 🟢',
      'diff_medium': 'Trung Bình 🟡',
      'diff_hard': 'Khó 🔴',
      'diff_ultimate': 'Đỉnh Cao 🌟',
      'completion_rate': 'Tỉ lệ: %rate%%',
      'overall_completion': 'Tiến độ tổng thể: %rate%%',
      'global_unlock_rate': '🌐 %rate%% người dùng đã đạt được',
      'rare_achievement_badge': '🔥 HIẾM (%rate%%)',
      'ultra_rare_badge': '🌟 BẢO VẬT (%rate%%)',
      'share_loading_image': 'Đang tải hình ảnh...',
      'share_rendering_card': 'Đang vẽ Card chia sẻ...',
      'share_text_caption': 'Chia sẻ khoảnh khắc từ ứng dụng Army 🐜',
      'share_error_prefix': 'Lỗi khi tạo ảnh chia sẻ: %error%',
      'google_client_config_error': 'Lỗi cấu hình Đăng nhập Google trên thiết bị. Vui lòng thử lại sau ít phút.',
      'crash_title': 'Đã Xảy Ra Sự Cố Hệ Thống 🛠️',
      'crash_subtitle': 'Army đã tự động chặn luồng lỗi để bảo vệ dữ liệu của bạn. Hãy thử khởi động lại hoặc dọn bộ nhớ tạm.',
      'crash_log_header': 'Chi tiết sự cố (Error Log):',
      'crash_no_stacktrace': 'Không có dấu vết bộ nhớ (No stack trace available).',
      'crash_restart_app': 'Khởi Động Lại App 🔄',
      'crash_clear_cache': 'Xóa Cache 🧹',
      'crash_copy_log': 'Sao Chép Log 📋',
      'crash_toast_cleared': 'Đã dọn dẹp bộ nhớ tạm!',
      'crash_toast_copied': 'Đã sao chép nhật ký lỗi vào khay nhớ tạm 📋',
      'ach_posts_title': 'Khoảnh Khắc Bất Tận 📸',
      'ach_posts_desc': 'Gửi các bức ảnh & video khoảnh khắc tới bạn bè',
      'ach_posts_t1': 'Khởi Đầu 🥉',
      'ach_posts_t2': 'Tập Sự 🥈',
      'ach_posts_t3': 'Nhiếp Ảnh Gia 🥇',
      'ach_posts_t4': 'Bậc Thầy Khoảnh Khắc 💎',
      'ach_posts_t5': 'Huyền Thoại Army 👑',
      'ach_friends_title': 'Kết Bạn Tứ Phương 🤝',
      'ach_friends_desc': 'Kết nối và thêm bạn bè mới vào danh sách',
      'ach_friends_t1': 'Làm Quen 🥉',
      'ach_friends_t2': 'Cạ Cứng 🥈',
      'ach_friends_t3': 'Hội Bạn Thân 🥇',
      'ach_friends_t4': 'Ngôi Sao Kết Nối 💎',
      'ach_friends_t5': 'Vua Tình Bạn 👑',
      'ach_streak_title': 'Giữ Nhịp Thắp Lửa 🔥',
      'ach_streak_desc': 'Duy trì chuỗi đăng bài Streak liên tục hằng ngày',
      'ach_streak_t1': 'Nhen Nhóm 🥉',
      'ach_streak_t2': 'Ngọn Lửa Bền Bỉ 🥇',
      'ach_streak_t3': 'Nữ Hoàng Thắp Lửa 👑',
      'ach_love_title': 'Tình Yêu Vĩnh Cửu 💖',
      'ach_love_desc': 'Kỷ niệm số ngày bên nhau ở Chế độ Cặp Đôi',
      'ach_love_t1': 'Chớm Nở 💖',
      'ach_love_t2': 'Gắn Kết 🥇',
      'ach_love_t3': 'Trăm Năm Hạnh Phúc 💎',
      'ach_stamps_title': 'Dấu Ấn Vintage 📮',
      'ach_stamps_desc': 'Chụp và tạo các bức ảnh Tem Thư Bưu Chính',
      'ach_stamps_t1': 'Thư Tay 📮',
      'ach_stamps_t2': 'Bưu Điện Cổ 💎',
      'ach_spotify_title': 'Giai Điệu Cảm Xúc 🎵',
      'ach_spotify_desc': 'Đính kèm nhạc Spotify 30s vào bài đăng',
      'ach_spotify_t1': 'Giai Điệu Hay 🎵',
      'ach_spotify_t2': 'Nhạc Trưởng 👑',
      'ach_streak_365_title': 'Triệu Phú Streak ⚡',
      'ach_streak_365_desc': 'Duy trì chuỗi đăng bài Streak liên tục đúng 365 ngày không nghỉ',
      'ach_streak_365_t1': 'Huyền Thoại 365 Ngày ⚡',
      'ach_ultimate_ant_title': 'Thủ Lĩnh Armi 🐜👑',
      'ach_ultimate_ant_desc': 'Gửi tròn 1000 khoảnh khắc ảnh/video tới bạn bè',
      'ach_ultimate_ant_t1': 'Thủ Lĩnh Tối Thượng 🐜👑',
      'ach_chat_title': 'Bậc Thầy Trò Chuyện 💬',
      'ach_chat_desc': 'Gửi tin nhắn & phản hồi khoảnh khắc cho bạn bè',
      'ach_chat_t1': 'Tán Gẫu 🥉',
      'ach_chat_t2': 'Sôi Nổi 🥈',
      'ach_chat_t3': 'Tâm Giao 🥇',
      'ach_chat_t4': 'Bậc Thầy Trò Chuyện 💎',
      'ach_vip_title': 'Thượng Khách Gold Pass 👑',
      'ach_vip_desc': 'Kích hoạt hoặc sở hữu gói hội viên Army Gold Pass 🌟',
      'ach_vip_t1': 'Thượng Khách VIP 🌟',
      'ach_cam_theme_title': 'Biến Hình Camera 🎨',
      'ach_cam_theme_desc': 'Mở khóa & thay đổi các chủ đề khung viền Camera',
      'ach_cam_theme_t1': 'Sáng Tạo 🎨',
      'ach_cam_theme_t2': 'Phù Thủy Sắc Màu 💎',
      'ach_app_icons_title': 'Sưu Tầm Icon 📱',
      'ach_app_icons_desc': 'Sở hữu và thay đổi các mẫu Icon 3D độc quyền',
      'ach_app_icons_t1': 'Mới Mẻ 📱',
      'ach_app_icons_t2': 'Phong Cách 🥇',
      'ach_app_icons_t3': 'Vua Sưu Tầm 💎',
      'gold_pass_paywall_title': 'Army Gold Pass 🌟',
      'gold_pass_paywall_subtitle': 'Đặc Quyền Hội Viên Thượng Hạng',
      'subscribe_now': 'Đăng Ký Ngay',
      'restore_purchases': 'Khôi Phục Giao Dịch',
      'monthly_plan': 'Gói Tháng',
      'yearly_plan': 'Gói Năm',
      'save_percentage': 'TIẾT KIỆM %count%%',
      'vip_feature_adfree': 'Ẩn 100% quảng cáo toàn ứng dụng',
      'vip_feature_unlimited_restore': 'Khôi phục chuỗi Streak không giới hạn',
      'vip_feature_icons': 'Sở hữu vĩnh viễn 25 Icon App 3D VIP',
      'vip_feature_spotify': 'Đính kèm nhạc Spotify 30s không giới hạn',
      'vip_feature_watermark': 'Tải ảnh/video sạch 100% không watermark',
      'vip_feature_security': 'Cho phép chụp/quay màn hình (Android)',
      'ios_iap_unsupported': '⚠️ Tính năng đăng ký gói Army Gold Pass 🌟 hiện chưa hỗ trợ trên thiết bị iOS. Vui lòng quay lại sau!',
      'purchase_success_toast': '🎉 Đăng ký Army Gold Pass thành công!',
      'purchase_restored_toast': '🎉 Khôi phục giao dịch thành công!',
      'restore_wrong_account': '❌ Giao dịch này thuộc về tài khoản Gmail khác. Không thể khôi phục.',
      'restore_no_purchase': 'Không tìm thấy giao dịch nào để khôi phục.',
      'restore_expired': 'Gói đã mua đã hết hạn.',
      'vip_downgraded_toast': 'Gói Army Gold Pass đã hết hạn. Đã về gói Free.',
      'vip_status_active': 'Đang hoạt động ✅',
      'vip_status_expired': 'Đã hết hạn ❌',
      'vip_status_cancelled': 'Đã hủy gia hạn',
      'vip_plan_monthly': 'Gói Tháng',
      'vip_plan_yearly': 'Gói Năm',
      'vip_expiry_date': 'Hết hạn: %date%',
      'vip_upgrade_btn': 'Nâng cấp gói',
      'vip_cancel_renewal': 'Hủy gia hạn',
      'vip_section_title': 'Gói đăng ký của bạn',
      'shield_ready': 'Lá Chắn Tự Động: Đang sẵn sàng 🛡️',
      'shield_used': 'Lá Chắn Tự Động: Đã dùng tuần này 🛡️ (Tự động hồi vào Thứ Hai)',
      'restore_credits_label': 'Số lượt khôi phục tích lũy: %count% lượt ⚡',
      'restore_vip_unlimited': 'Hội viên Gold Pass: Khôi phục Vô Hạn 👑',
      'watch_ad_btn': 'Xem Quảng Cáo 🎬',
      'watch_ad_to_restore_title': 'Nhận Lượt Khôi Phục',
      'watch_ad_to_restore_desc': 'Xem hết video quảng cáo để nhận thêm 1 lượt khôi phục chuỗi 🔥',
      'ad_reward_success': '🎬 Đã nhận +1 Lượt Khôi Phục chuỗi! Số lượt hiện có: %count%',
      'ad_limit_reached': '⚠️ Bạn đã đạt giới hạn xem 5 quảng cáo khôi phục chuỗi hôm nay. Vui lòng quay lại vào ngày mai!',
      'ad_not_finished': '⚠️ Bạn chưa xem hết quảng cáo nên chưa nhận được phần thưởng!',
      'ad_load_failed': '⚠️ Không thể tải video quảng cáo. Vui lòng kiểm tra lại kết nối mạng!',
      'restore_success_toast': '🔥 Đã khôi phục chuỗi %count% ngày thành công! Hãy gửi 1 khoảnh khắc hôm nay để duy trì nhịp nhé!',
      'admin_quota_tab': 'Thuê Bao & Lượt 👑',
      'admin_live_events': 'LIVE EVENTS COUNTER 📊',
      // 'admin_no_users': 'Không có người dùng nào',
      'admin_gold_pass': 'Gold Pass: %status%',
      'admin_restore_credits': 'Lượt khôi phục: %count%',
      'admin_monthly_restore': 'Khôi phục tháng: %status%',
      'admin_edit_streak': 'Sửa số lượt Streak',
      'admin_edit_streak_title': 'Số lượt khôi phục Streak',
      'admin_enter_credits': 'Nhập số lượt',
      'admin_save_btn': 'Lưu',
      'admin_cancel_btn': 'Hủy',
      'admin_credits_updated': 'Đã cập nhật số lượt khôi phục cho %user% thành %val%',
      'admin_monthly_reset': 'Đã reset lượt miễn phí hàng tháng cho %user%',
      'admin_gold_pass_updated': 'Đã cập nhật trạng thái Gold Pass của %user%',
      'admin_users_tab_count': 'Thành viên (%count%)',
      'admin_posts_tab': 'Bài viết',
      'admin_reports_tab': 'Báo cáo',
      'admin_role_admin': 'Quản trị viên',
      'admin_role_user': 'Người dùng',
      'admin_status_used': 'Đã dùng ❌',
      'admin_status_ready': 'Sẵn sàng ✅',
      'admin_cancel_gold_pass': 'Hủy Gold Pass',
      'admin_grant_gold_pass': 'Cấp Gold Pass 🌟',
      'admin_reset_monthly_free_tooltip': 'Reset lượt khôi phục miễn phí hàng tháng',
      'admin_event_app_open': 'Mở ứng dụng (app_open) 📱',
      'admin_event_login': 'Đăng nhập (login) 🔑',
      'admin_event_create_post': 'Đăng khoảnh khắc (create_post) 📸',
      'admin_event_send_message': 'Gửi tin nhắn (send_message) 💬',
      'admin_event_add_reaction': 'Thả cảm xúc (add_reaction) ❤️',
      'weather_loading': 'Đang tải nhiệt độ vị trí...',
      'weather_updated_toast': '🌡️ Đã cập nhật nhiệt độ vị trí!',
      'tap_to_refresh_weather': 'Bấm trực tiếp vào caption để cập nhật',
      'ad_sponsored_tooltip': 'Quảng cáo này giúp duy trì ứng dụng Army miễn phí cho tất cả mọi người. Đăng ký Army Gold Pass 🌟 để ẩn toàn bộ quảng cáo.',
      'ad_sponsored_label': 'ⓘ Được tài trợ',
      'ad_loading_text': 'Đang tải quảng cáo tài trợ...',
      'ad_failed_title': 'Không thể tải quảng cáo',
      'ad_failed_desc': 'Vui lòng kiểm tra lại kết nối mạng hoặc thử lại.',
      'retry_btn_label': 'Thử lại',
      'restore_checking_toast': 'Đang kiểm tra lịch sử giao dịch...',
      'restore_unsupported_platform': 'Tính năng khôi phục giao dịch không khả dụng trên thiết bị này.',
      'restore_connect_error': 'Không thể kết nối với cửa hàng để khôi phục giao dịch.',
      'restore_network_error': '⚠️ Không có kết nối mạng! Vui lòng kiểm tra lại Internet.',
    },
    'en': {
      'app_title': 'Army',
      'splash_subtitle': 'Locket Clone UI',
      'language_select_title': 'Select Language',
      'format_select_title': 'Format Settings',
      'continue': 'Continue',
      'save': 'Save Settings',
      'cancel': 'Cancel',
      'accept_all': 'Accept All',
      'reject_all': 'Reject All',
      'feature_coming_soon': 'Feature coming soon',
      'self_friend_blocked': 'You cannot send a friend request to yourself!',
      'add_friend': 'Add Friend',
      'add_friend_hint': 'Enter the exact username of the person you want to add',
      'send_invite': 'Send Invite',
      'friend_added': 'Accepted friend request from %user%',
      'zoom_rear_only': 'Zoom feature is only supported on the rear camera',
      'just_now': 'Right now',
      'mins_ago': 'mins ago',
      'hours_ago': 'hours ago',
      'days_ago': 'days ago',
      'offline': 'Offline',
      'online': 'Online',
      'show_timestamp': 'Show Timestamp',
      'friends_count': '%count% friends',
      'rollcall_title': 'Rollcall - Right Now',
      'select_photo': 'CHOOSE PHOTO',
      'history_label': 'History',
      'double_tap': 'Double Tap',
      'add_new_friend': 'Add a new friend',
      'search_friend_placeholder': 'Search name or username (e.g. @hoa456)',
      'invites_title': 'Invites',
      'friends_title': 'Friends',
      'accept': 'Accept',
      'decline': 'Decline',
      'cancel_request': 'Cancel Request',
      'best_friend': 'Best Friend',
      'love_invite_sent': 'Love invite sent',
      'single_camera_found': 'Only 1 camera found on device',
      'photo_captured': '📸 Locket photo captured!',
      'camera_viewfinder': 'Army Viewfinder',
      'history_photos_title': 'Photo History',
      'photo_item': 'Photo',
      'change_language': 'Change Language',
      'settings': 'Settings',
      'send_to': 'Send to...',
      'add_message_caption': 'Add a message...',
      'all_friends': 'All',
      'photo_saved': '💾 Photo saved to gallery!',
      'photo_sent': '🚀 Locket sent successfully!',
      'crop_image_title': 'Crop Locket Image',
      'crop_image_hint': 'Drag to move, pinch or use slider to zoom.',
      'crop_save': 'Crop & Use',
      'zoom_image': 'Zoom',
      'cropping_image': 'Processing cropped image...',
      'permission_title': 'App Permissions Required',
      'permission_desc': 'Army requires Camera, Photos, and Notification access to capture & share Lockets.',
      'permission_grant': 'Grant Permissions',
      'permission_granted_toast': '✅ App permissions granted successfully!',
      'noti_reaction_title': '❤️ New Reaction',
      'noti_reaction_body': '%sender% reacted to your Locket photo!',
      'noti_message_title': '💬 New Message',
      'noti_message_body': '%sender%: %content%',
      'noti_reply_title': '💬 Feed Reply',
      'noti_reply_body': '%sender% replied to your photo!',
      'noti_morning_title': '☀️ Good Morning Locket!',
      'noti_morning_body': 'Don\'t forget to share your morning moment with friends!',
      'noti_evening_title': '⏰ Evening Deadline Reminder!',
      'noti_evening_body': 'It\'s time to send your daily Locket photo to your best friends!',
      'aspect_ratio': 'Locket Aspect Ratio',
      'aspect_1_1': '1:1 Square (Locket Standard 🔳)',
      'aspect_4_3': '4:3 Rectangle (Extended 📱)',
      'format_unit': 'Data Size Unit',
      'time_format': 'Timestamp Format',
      'activity_format': 'Activity Status Format',
      'login_title': 'Sign In to Army',
      'login_subtitle': 'Sign in to capture & share Lockets with close friends',
      'email_or_username': 'Email or Username',
      'password': 'Password',
      'login_btn': 'Sign In',
      'google_login_btn': 'Sign in with Google',
      'no_account': 'Don\'t have an account?',
      'create_new_account': 'Create new account',
      'register_title': 'Create Army Account',
      'select_avatar_title': 'Choose Profile Avatar (10 Presets)',
      'email_domain_hint': 'e.g. user@gmail.com, icloud.com...',
      'dob_title': 'Date of Birth (DOB)',
      'dob_hint': 'Select date of birth (DD/MM/YYYY)',
      'confirm_password': 'Confirm Password',
      'register_btn': 'Register Account',
      'bad_word_error': '🚫 Caption contains forbidden word ("%word%")! Please edit.',
      'google_login_success': '🌐 Google Sign-In successful! Welcome %user%',
      'login_success': '👋 Signed in successfully! Welcome %user%',
      'register_success': '🎉 Registration successful! Logged in as %user%',
      'gms_warning_title': '⚠️ Google Play Services Warning',
      'gms_warning_desc': 'Your device lacks or has disabled Google Play Services. Features such as Google Sign-In and GPS Location will be automatically disabled.',
      'gms_warning_btn': 'Got it & Continue',
      'gms_disabled_tooltip': 'Google Play Services unavailable on this device',
      'camera_error_title': 'Camera Initialization Error',
      'camera_retry_btn': 'Retry Camera',
      'camera_in_use_error': 'Camera device is busy or in use by another process. Tap retry to release.',
      'no_camera_found': 'No camera device found on system',
      'private_only': 'Only Me',
      'camera_access_denied': 'Camera access denied. Please grant permission in Settings.',
      'lover': 'Lover 💖',
      'private': 'Private',
      'public': 'Public',
      'voice_recording_done': '🎙️ Voice note recorded (%sec%s)!',
      'voice_recording_in_progress': 'Recording (%sec%s)... Stop',
      'voice_attached': '🎵 Voice attached (15s)',
      'add_voice': 'Add voice (15s)',
      'get_gms_location': '📍 Grant Permission & Get Location',
      'getting_gms_location': '📡 Fetching location...',
      'gms_location_fetched_toast': '📍 Location retrieved: %location%',
      'location_permission_granted': '✅ Location permission granted successfully!',
      'location_caption_grey': 'Location',
      'refetch_location': 'Re-fetch location',
      'mood_selected': 'Mood: %emoji%',
      'reaction_sent': '%emoji% Reacted!',
      'message_sent_to': '💬 Message sent to %user%!',
      'post_options_of': 'Post options for %user%',
      'save_image_device': 'Save photo to device',
      'image_saved_success': '💾 Photo saved successfully!',
      'report_post': 'Report post',
      'report_sent_success': '🚩 Report submitted!',
      'close_settings': 'Close Settings',
      'close_btn': 'Close',
      'admin_panel_title': 'ADMIN PANEL',
      'admin_stats_tab': 'Stats & Ranks',
      'admin_stats_overview': '📊 SYSTEM OVERVIEW STATS',
      'admin_total_army': 'TOTAL ARMY (POSTS)',
      'admin_total_users': 'TOTAL USERS',
      'admin_total_couples': 'LOVE COUPLES',
      'admin_total_interactions': 'TOTAL INTERACTIONS',
      'admin_today_posts': '+%count% today 🔥',
      'admin_today_users': '+%count% new today ⚡',
      'admin_couples_sub': 'Paired together ❤️',
      'admin_interactions_sub': 'Reactions & Hearts',
      'admin_top_streak_title': '🏆 TOP LONGEST STREAKS',
      'admin_top_posters_title': '📸 TOP MOST ACTIVE POSTERS',
      'admin_days_unit': 'days',
      'admin_posts_unit': 'posts',
      'admin_delete_user_title': 'Delete User',
      'admin_delete_user_confirm': 'Are you sure you want to delete user %user%?',
      'admin_delete_post_title': 'Delete Post',
      'admin_delete_post_confirm': 'Are you sure you want to delete this post?',
      'admin_panel_subtitle': 'Manage Users, Posts, and Reports',
      'admin_delete_btn': 'Delete',
      'admin_deleted_user_success': '🗑️ Deleted user %user%!',
      'admin_resolve_report_success': '✅ Report resolved and notification sent to %reporter%',
      'admin_no_users': 'No users found',
      'admin_role_created': 'Role: %role% | Created: %date%',
      'admin_you': 'You',
      'admin_unfriend_tooltip': 'Unfriend',
      'admin_friend_tooltip': 'Add Friend',
      'admin_unfriend_success': '💔 Unfriended %user%',
      'admin_friend_success': '🤝 Friended %user%',
      'admin_no_posts': 'No posts found',
      'admin_no_caption': 'No caption',
      'admin_deleted_post_success': '🗑️ Post deleted!',
      'admin_no_reports': 'No reports found',
      'admin_report_by': 'Reported by: %reporter%',
      'admin_report_resolved': 'RESOLVED',
      'admin_report_pending': 'PENDING',
      'admin_report_target': 'Target: %target%',
      'admin_report_content': 'Content: "%content%"',
      'admin_resolve_fcm_btn': 'Resolve & Send FCM',
      'admin_reporter_notified': 'Notification sent to reporter',
      'admin_refresh_tooltip': 'Reload data',
      'delete_post_this': 'Delete this post',
      'post_deleted_success': '🗑️ Post deleted!',
      'no_posts_yet': 'No posts yet!',
      'type_message_hint': 'Send a message...',
      'replying_to': 'Replying to %user%',
      'replying_to_self': 'Replying to yourself',
      'reply_label': 'Reply',
      'copy_label': 'Copy',
      'message_copied_toast': '📋 Message copied to clipboard!',
      'friend_reacted_message': '%sender% reacted to the message',
      'memory_title': 'Anniversary Title',
      'memory_hint': 'e.g. Trip to Da Lat...',
      'use_default': 'Use Default',
      'memory_saved': 'Anniversary title saved!',
      'upload_error': '❌ Error uploading photo: %error%',
      'email_invalid_domain': 'Please enter an Email from Gmail, iCloud, or Microsoft (Outlook, Hotmail)!',
      'confirm_password_mismatch': 'Passwords do not match!',
      'register_failed': 'Registration failed!',
      'login_failed': 'Sign in failed!',
      'google_login_failed': 'Google sign-in failed!',
      'email_address_label': 'Email Address',
      'display_name_label': 'Display Name',
      'display_name_hint': 'Enter your display name',
      'username_label': 'Username',
      'username_hint': 'e.g. @hoangnam872',
      'username_desc': 'Username is used for adding friends and sharing your private profile.',
      'password_min_hint': 'At least 6 characters',
      'confirm_password_hint': 'Re-enter password above',
      'author_reactions_title': 'Reactions on post',
      'no_reactions_yet': 'No reactions yet',
      'reactions_count': '%count% reactions',
      'play_voice': 'Play Voice (%sec%s)',
      'pause_voice': 'Pause Voice',
      'share_post': 'Share post',
      'share_link_copied': '🔗 Share link copied!',
      'friends_badge': 'Friends',
      'copy_invite_link_success': '📋 Copied invite link: %link%',
      'edit_avatar_title': 'Change Profile Avatar',
      'avatar_emoji_changed': 'Avatar changed successfully!',
      'posts_badge': 'Army',
      'streak_days': 'days',
      'feed_display_mode': 'Feed Display Mode',
      'thought_bubbles': 'Thought bubbles',
      'photos_only': 'Photos',
      'choose_feed_mode_title': 'Choose Feed Grid display mode',
      'widget_data_source': 'Widget Data Source',
      'widget_size': 'Widget Size',
      'block_user': 'Block',
      'download_photo': 'Download photo',
      'filter_everyone': 'Everyone',
      'filter_best_friends': 'Best Friends',
      'filter_friends': 'Me',
      'share_profile': 'Share',
      'streak_label': 'Streak',
      'camera_theme_title': 'Choose camera theme',
      'camera_theme_subtitle': 'Change camera background and border',
      'change_app_icon': 'Change App Icon',
      'settings_title': 'Settings',
      'language_settings': 'Language',
      'logout': 'Log Out',
      'logout_confirm_title': 'Log Out?',
      'add_friend_to_chat_hint': 'Add friends to start chatting!',
      'report_title': 'Report',
      'block_title': 'Block',
      'start_conversation_title': 'Start a conversation!',
      'start_conversation_desc': 'Reply to one of their moments to start a conversation',
      'blocked_user_success': 'Blocked %user%!',
      'logout_confirm_msg': 'Are you sure you want to log out of this account?',
      'logout_confirm_btn': 'Log Out',
      'search_start_hint': 'Enter name or username to search...',
      'friendship_me': 'You',
      'friendship_friends': 'Friends',
      'friendship_pending': 'Pending',
      'friendship_add': 'Add friend',
      'friend_options_title': 'Friend Options',
      'remove_best_friend': 'Remove from best friends',
      'add_best_friend': 'Add to best friends',
      'remove_friend': 'Unfriend',
      'remove_friend_confirm_title': 'Unfriend %user%?',
      'remove_friend_confirm_desc': 'You will no longer see each other\'s moments.',
      'block_confirm_title': 'Block %user%?',
      'block_confirm_desc': 'You will not be able to send messages or see each other\'s moments.',
      'my_username_label': 'Your username',
      'username_copied': 'Copied username: %user%',
      'account_created_at': 'Created: %date%',
      'streak_active_msg': 'Streak active 🔥: %count% days!',
      'streak_countdown': '%time% remaining to continue streak 🔥',
      'streak_below_3_msg': 'Streak 🔥: %count% days',
      'profile_settings_tooltip': 'Profile & Settings (%user%)',
      'friends_list_tooltip': 'Friends list (%count% friends)',
      'chat_messages_tooltip': 'Chat & Messages',
      'gallery_tooltip': 'Upload from gallery (Key G)',
      'shutter_tooltip': 'Take Locket photo (Space)',
      'flip_camera_tooltip': 'Flip camera lens (Key C)',
      'feed_trigger_tooltip': 'Feed & Post History (Arrow Down / PageDown / Mouse Scroll)',
      'flash_off_tooltip': 'Flash Off',
      'flash_on_tooltip': 'Always On (Torch)',
      'flash_auto_tooltip': 'Auto (Capture Flash)',
      'flash_off_toast': '⚡ Flash Off',
      'flash_on_toast': '🔦 Flash Always On',
      'flash_auto_toast': '⚡ Auto Flash',
      'zoom_tooltip': 'Camera zoom settings',
      'zoom_preset_toast': '🔍 Camera zoom: %zoom%x',
      'loading_friends_list': 'Loading friends list...',
      'no_friends_yet': 'No friends yet',
      'no_internet_title': 'No Internet Connection',
      'no_internet_desc': 'Please connect to the internet to use the application.',
      'exit_app_btn': 'Exit Application',
      'press_back_again_to_exit': 'Press back again to exit application',
      'battery_critical_title': 'Battery Critical 🔋',
      'battery_critical_desc': 'Your device battery is extremely low (<= 5%). Please connect a charger to continue using the application.',
      'connection_lost_toast': 'Internet connection lost! The app will exit in %sec% seconds...',
      'connection_restored_toast': 'Internet connection restored! Synchronizing...',
      'countdown_exit_msg': 'No internet connection! Exit in:',
      'unfriend_success': 'Unfriended %user%',
      'cannot_drag_normal_above_priority': 'Cannot drag a normal friend above Best Friends or Lovers!',
      'cannot_drag_best_below_priority': 'Best friends must always be at the top of the list!',
      'cannot_drag_lover_above_best': 'Cannot drag Lovers above Best Friends!',
      'cannot_drag_lover_below_normal': 'Lovers must always be above normal friends!',
      'friend_order_updated': 'Friend order updated!',
      'sent_invites': 'Sent Invites',
      'pending_acceptance': 'Pending acceptance...',
      'request_cancelled': 'Friend request cancelled!',
      'streak_sheet_title': 'Daily Army Pulse',
      'streak_current_days': 'Current pulse: %count% days',
      'streak_keep_subtitle': 'Keep your Army pulse alive by sharing a moment today!',
      'streak_milestones_title': 'Army Milestones',
      'streak_next_title': 'Next Milestone',
      'streak_add_days_hint': 'Add %count% more days to unlock %name%',
      'streak_restore_btn': 'Restore Streak',
      'streak_countdown_tooltip': 'Only %time% left to post and keep your streak alive...',
      'streak_current_badge': 'Active',
      'streak_unlocked_badge': 'Unlocked',
      'streak_m_3': 'Ant Sprout',
      'streak_m_7': 'Soldier Ant',
      'streak_m_14': 'Worker Ant',
      'streak_m_30': 'Anthill',
      'streak_m_45': 'Golden Ant',
      'streak_m_60': 'Veteran Ant',
      'streak_m_75': 'General Ant',
      'streak_m_90': 'Queen Ant',
      'coachmark_completed': '🎉 Armi tour completed! Enjoy your Army experience!',
      'replay_coachmark': 'Replay Armi Tour 🐜',
      'coachmark_step_1': 'Hello! I\'m Armi 🐜. This is your avatar and personal profile page!',
      'coachmark_step_2': 'Click here to view your Friends list and pending friend requests!',
      'coachmark_step_3': 'Click the shutter button in the center to capture and share your Locket moments!',
      'replied_to_post': 'Replied to a post',
      'email_in_use_error': 'This email is already in use!',
      'username_exists_error': 'This username already exists!',
      'incorrect_password_error': 'Incorrect password provided!',
      'account_not_found_error': 'No account found with this Email or Username!',
      'google_auth_failed': 'Google authentication failed!',
      'google_account_error': 'Could not authenticate Google account info!',
      'google_login_cancelled': 'Google login cancelled!',
      'holiday_30_4_1_5': 'Celebrate Victory Day 30/4 & International Workers\' Day 1/5!',
      'holiday_2_9': 'Celebrate Vietnam National Day 2/9!',
      'holiday_20_11': 'Celebrate Vietnam Teachers\' Day 20/11! 💐',
      'tet_countdown_days': 'Only %days% days left until Lunar New Year %name% 🧧',
      'tet_new_year': '🧧 Happy Lunar New Year %name%! Best wishes for the New Year! 🌸',
      'tet_default': 'Lunar New Year %name% 🧧',
      'blur_overlay_enabled': 'Post hiding enabled! 👁️',
      'blur_overlay_disabled': 'Post hiding disabled! 👁️',
      'tet_wish_1': 'May all your wishes come true! 🧧',
      'tet_wish_2': 'Prosperity and wealth! 🌸',
      'tet_wish_3': 'Good fortune and peace! 🍊',
      'tet_wish_4': 'Abundant wealth and luck! 💰',
      'tet_wish_5': 'Great health and longevity! 💪',
      'tet_wish_6': 'Smile like a flower! 😄',
      'tet_wish_7': 'May all your dreams come true! ✨',
      'tet_wish_8': 'Smooth sailing in everything! 🎈',
      'tet_wish_9': '%user%\'s Tet vibe is here! 🧧',
      'tet_wish_10': 'This is %user%\'s Lunar New Year %name%! 🌸',
      'tet_wish_11': 'Send %user% some lucky money! 🧧',
      'tet_wish_12': 'Wishing %user% a wonderful New Year! 😄',
      'zodiac_aries': '♈ Energetic Aries %user%!',
      'zodiac_taurus': '♉ Steadfast & loyal Taurus %user%!',
      'zodiac_gemini': '♊ Witty & curious Gemini %user%!',
      'zodiac_cancer': '♋ Loving & caring Cancer %user%!',
      'zodiac_leo': '♌ Confident & shining Leo %user%!',
      'zodiac_virgo': '♍ Detail-oriented & elegant Virgo %user%!',
      'zodiac_libra': '♎ Peace-loving & balanced Libra %user%!',
      'zodiac_scorpio': '♏ Mysterious & charming Scorpio %user%!',
      'zodiac_sagittarius': '♐ Free-spirited & adventurous Sagittarius %user%!',
      'zodiac_capricorn': '♑ Responsible & hardworking Capricorn %user%!',
      'zodiac_aquarius': '♒ Creative & unique Aquarius %user%!',
      'zodiac_pisces': '♓ Dreamy & kind-hearted Pisces %user%!',
      'love_menu_title': 'Couple Mode',
      'set_love_date': 'Choose anniversary date',
      'send_love_invite_btn': 'Send love invitation',
      'love_invitation_title': 'Love Couple Invitation 💖',
      'love_invitation_desc': '%user% wants to couple with you and save sweet moments starting from %date%.',
      'anniversary_days': '%days% Days Together',
      'break_up_confirm_title': 'Break relationship?',
      'break_up_confirm_desc': 'You and your partner will no longer share the Love Feed and anniversary counter.',
      'break_up_btn': 'Break Up',
      'love_feed_title': 'Love Feed 💖',
      'empty_love_feed': 'No love moments shared yet! Send a Locket to your partner now.',
      'status_bubble_hint': "What's on your mind?",
      'love_invite_pending_error': 'You or the partner already has a pending love invitation!',
      'waiting_response': 'Waiting for response...',
      'love_setup_waiting_desc': 'Your couple invitation has been sent to %user%. Waiting for them to accept to start counting days!',
      'revoke_invite_btn': 'Revoke Invitation',
      'revoke_invite_success': 'Couple invitation revoked.',
      'select_friend_to_couple': 'Please select a friend to couple!',
      'love_invite_sent_success': 'Love invitation sent!',
      'mic_permission_denied': '⚠️ Microphone permission denied!',
      'loading_profile_data': 'Loading profile data...',
      'army_building_timeline': 'Army is building your timeline...',
      'love_couple_success_toast': '💖 Congratulations! You have successfully coupled!',
      'love_couple_declined_toast': 'Couple invitation declined.',
      'break_up_success_toast': '💔 Successfully broken relation.',
      'break_up_failed_toast': 'Error breaking relationship!',
      'love_status_updated_toast': 'New status updated!',
      'love_status_hint': 'Enter status (e.g. "I am hungry")',
      'love_cannot_couple_self': 'Cannot couple with yourself',
      'love_you_already_coupled': 'You are already coupled!',
      'love_you_have_pending': 'You have a pending couple invitation. Please resolve it first!',
      'love_user_not_found': 'User "%user%" not found',
      'love_user_already_coupled': '%user% is already coupled!',
      'love_user_has_pending': '%user% has a pending couple invitation with someone else!',
      'not_logged_in_error': 'Not logged in',
      'love_invite_sent_success_to': 'Couple invitation sent to %user%',
      'love_invite_send_error': 'Error sending invitation: %error%',
      'love_accept_error': 'Error accepting invitation: %error%',
      'break_up_error_toast': 'Error breaking relationship: %error%',
      'cannot_friend_self': 'Cannot friend yourself',
      'friend_not_found': 'User "%user%" not found',
      'already_friends': 'Already friends',
      'friend_request_already_sent': 'Friend request already sent',
      'friend_request_sent_to': 'Friend request sent to %user%',
      'google_login_error': 'Google Sign-In Error: %error%',
      'love_status_coupled': 'Coupled with you 💖',
      'love_status_pending_received': 'Sent you a couple invitation! 📬',
      'love_days_together_label': 'Days Together',
      'anniversary_date_label': 'Anniversary date: %date%',
      'recap_button_title': 'Moment Recap 🌟',
      'recap_screen_title': 'Moment Recap',
      'recap_weekly': 'Weekly Recap',
      'recap_monthly': 'Monthly Recap',
      'recap_select_period': 'Select recap period',
      'recap_no_posts': 'No moments shared in this period!',
      'recap_posts_sent': 'You shared %count% moments!',
      'recap_active_days': 'Active days: %days% days',
      'recap_with_lover': 'You and %lover% exchanged %count% moments!',
      'recap_with_friends': 'You shared moments with %count% friends!',
      'recap_top_mood': 'Your top mood/emoji',
      'recap_top_caption': 'Most memorable caption',
      'recap_memories': 'MEMORIES 📸',
      'recap_together': 'TOGETHER 🤝',
      'recap_weekly_desc': '7 days of moments',
      'recap_monthly_desc': '30 days of moments',
      'recap_default_weekly_caption': 'A wonderful week!',
      'recap_default_monthly_caption': 'An awesome month!',
      'rollcall_join': 'Join Rollcall to unlock your friends\' photos! 🔒',
      'rollcall_btn_join': 'Capture Now 📸',
      'rollcall_prompt_label': 'Rollcall Challenge 📣',
      'rollcall_responses_title': 'Rollcall Responses',
      'rollcall_no_responses': 'No one has joined Rollcall today!',
      'rollcall_activated': 'Rollcall mode activated! 📣',
      'report_resolved_title': 'Report Resolved',
      'report_resolved_body': 'Your report has been reviewed and resolved.',
      'no_reactions_summary': 'No reactions yet',
      'reactions_summary_count': '%count% people reacted',
      'reacted_status': 'Reacted',
      'recap_daily': 'Daily Recap',
      'recap_daily_desc': 'Your day today',
      'recap_yearly': 'Yearly Recap',
      'recap_yearly_desc': 'Memories of the past 365 days',
      'recap_all_time': 'All-Time Recap',
      'recap_all_time_desc': 'All moments from the beginning',
      'recap_stat_first_post': 'First post:',
      'recap_stat_most_active': 'Most active:',
      'recap_stat_reactions_received': 'Reactions:',
      'recap_active_morning': 'Morning 🌅 (04:00 - 11:00)',
      'recap_active_afternoon': 'Afternoon ☀️ (11:00 - 17:00)',
      'recap_active_evening': 'Evening 🌆 (17:00 - 22:00)',
      'recap_active_night': 'Night 🌌 (22:00 - 04:00)',
      'recap_default_daily_caption': 'A day full of memories!',
      'recap_default_custom_caption': 'A wonderful period!',
      'achievements_title': 'Army Achievements 🏆',
      'achievements_subtitle': 'Unlock milestones & earn exclusive badges',
      'achievement_unlocked': 'Unlocked',
      'achievement_locked': 'Locked',
      'unlock_condition': 'Unlock Condition',
      'current_progress': 'Current Progress',
      'max_tier_reached': 'Max Tier Reached 💎',
      'tier_label': 'Tier %tier%/%max% • %name%',
      'next_tier_target': 'Next tier: %target%',
      'roadmap_title': 'Badge Roadmap',
      'achievements_header_count': '🏆 %unlocked% / %total% Badge Tiers',
      'target_label': 'Target: %target%',
      'cat_all': 'All',
      'cat_posts': 'Moments 📸',
      'cat_friends': 'Friends 🤝',
      'cat_streak': 'Streak 🔥',
      'cat_love': 'Love 💖',
      'cat_stamps': 'Stamps 📮',
      'cat_spotify': 'Music 🎵',
      'cat_ultimate': 'Ultimate 🌟',
      'diff_easy': 'Easy 🟢',
      'diff_medium': 'Medium 🟡',
      'diff_hard': 'Hard 🔴',
      'diff_ultimate': 'Ultimate 🌟',
      'completion_rate': 'Completion: %rate%%',
      'overall_completion': 'Overall Completion: %rate%%',
      'global_unlock_rate': '🌐 %rate%% of players unlocked this',
      'rare_achievement_badge': '🔥 RARE (%rate%%)',
      'ultra_rare_badge': '🌟 ULTRA RARE (%rate%%)',
      'share_loading_image': 'Loading image...',
      'share_rendering_card': 'Rendering share card...',
      'share_text_caption': 'Sharing a moment from Army app 🐜',
      'share_error_prefix': 'Error generating share card: %error%',
      'google_client_config_error': 'Google Sign-In configuration error on this device. Please try again later.',
      'crash_title': 'System Error Encountered 🛠️',
      'crash_subtitle': 'Army automatically caught an error to protect your data. Try restarting or clearing temporary cache.',
      'crash_log_header': 'Error Details (Error Log):',
      'crash_no_stacktrace': 'No stack trace available.',
      'crash_restart_app': 'Restart App 🔄',
      'crash_clear_cache': 'Clear Cache 🧹',
      'crash_copy_log': 'Copy Log 📋',
      'crash_toast_cleared': 'Temporary cache cleared!',
      'crash_toast_copied': 'Error log copied to clipboard 📋',
      'ach_posts_title': 'Endless Moments 📸',
      'ach_posts_desc': 'Send moment photos & videos to close friends',
      'ach_posts_t1': 'Beginner 🥉',
      'ach_posts_t2': 'Novice 🥈',
      'ach_posts_t3': 'Photographer 🥇',
      'ach_posts_t4': 'Moment Master 💎',
      'ach_posts_t5': 'Army Legend 👑',
      'ach_friends_title': 'Global Friendships 🤝',
      'ach_friends_desc': 'Connect and add new close friends',
      'ach_friends_t1': 'Newbie 🥉',
      'ach_friends_t2': 'Close Buddy 🥈',
      'ach_friends_t3': 'Friend Circle 🥇',
      'ach_friends_t4': 'Connection Star 💎',
      'ach_friends_t5': 'Friendship King 👑',
      'ach_streak_title': 'Flame Keepers 🔥',
      'ach_streak_desc': 'Maintain daily continuous post streak',
      'ach_streak_t1': 'Kindle Flame 🥉',
      'ach_streak_t2': 'Enduring Flame 🥇',
      'ach_streak_t3': 'Flame Queen 👑',
      'ach_love_title': 'Eternal Love 💖',
      'ach_love_desc': 'Celebrate days together in Couple Mode',
      'ach_love_t1': 'First Bloom 💖',
      'ach_love_t2': 'Bonded 🥇',
      'ach_love_t3': 'Everlasting Love 💎',
      'ach_stamps_title': 'Vintage Impressions 📮',
      'ach_stamps_desc': 'Capture and create Postal Stamp moments',
      'ach_stamps_t1': 'Handwritten 📮',
      'ach_stamps_t2': 'Vintage Post 💎',
      'ach_spotify_title': 'Emotional Melodies 🎵',
      'ach_spotify_desc': 'Attach 30s Spotify tracks to moments',
      'ach_spotify_t1': 'Sweet Melody 🎵',
      'ach_spotify_t2': 'Maestro 👑',
      'ach_streak_365_title': 'Streak Millionaire ⚡',
      'ach_streak_365_desc': 'Maintain 365 days of uninterrupted daily streak',
      'ach_streak_365_t1': '365-Day Legend ⚡',
      'ach_ultimate_ant_title': 'Armi Commander 🐜👑',
      'ach_ultimate_ant_desc': 'Send 1000 total moment photos & videos',
      'ach_ultimate_ant_t1': 'Supreme Commander 🐜👑',
      'ach_chat_title': 'Chat Master 💬',
      'ach_chat_desc': 'Send messages & replies to close friends',
      'ach_chat_t1': 'Chatter 🥉',
      'ach_chat_t2': 'Lively 🥈',
      'ach_chat_t3': 'Soulmate 🥇',
      'ach_chat_t4': 'Chat Master 💎',
      'ach_vip_title': 'Gold Pass VIP Guest 👑',
      'ach_vip_desc': 'Activate or own Army Gold Pass 🌟 subscription',
      'ach_vip_t1': 'VIP Guest 🌟',
      'ach_cam_theme_title': 'Camera Transformer 🎨',
      'ach_cam_theme_desc': 'Unlock & switch camera viewfinder themes',
      'ach_cam_theme_t1': 'Creative 🎨',
      'ach_cam_theme_t2': 'Color Wizard 💎',
      'ach_app_icons_title': 'Icon Collector 📱',
      'ach_app_icons_desc': 'Own & apply exclusive 3D app icons',
      'ach_app_icons_t1': 'Fresh Look 📱',
      'ach_app_icons_t2': 'Stylish 🥇',
      'ach_app_icons_t3': 'Collector King 💎',
      'gold_pass_paywall_title': 'Army Gold Pass 🌟',
      'gold_pass_paywall_subtitle': 'Premium Membership Privileges',
      'subscribe_now': 'Subscribe Now',
      'restore_purchases': 'Restore Purchases',
      'monthly_plan': 'Monthly',
      'yearly_plan': 'Yearly',
      'save_percentage': 'SAVE %count%%',
      'vip_feature_adfree': '100% ad-free experience',
      'vip_feature_unlimited_restore': 'Unlimited streak restorations',
      'vip_feature_icons': 'Forever own 25 premium 3D app icons',
      'vip_feature_spotify': 'Attach unlimited 30s Spotify tracks',
      'vip_feature_watermark': '100% clean photo & video downloads',
      'vip_feature_security': 'Bypass screenshot protection (Android)',
      'ios_iap_unsupported': '⚠️ Army Gold Pass 🌟 subscription is not supported on iOS yet. Please try again later!',
      'purchase_success_toast': '🎉 Subscribed to Army Gold Pass successfully!',
      'purchase_restored_toast': '🎉 Purchases restored successfully!',
      'restore_wrong_account': '❌ This purchase belongs to a different Gmail account.',
      'restore_no_purchase': 'No purchases found to restore.',
      'restore_expired': 'Your subscription has expired.',
      'vip_downgraded_toast': 'Army Gold Pass expired. Downgraded to Free.',
      'vip_status_active': 'Active ✅',
      'vip_status_expired': 'Expired ❌',
      'vip_status_cancelled': 'Cancelled',
      'vip_plan_monthly': 'Monthly Plan',
      'vip_plan_yearly': 'Yearly Plan',
      'vip_expiry_date': 'Expires: %date%',
      'vip_upgrade_btn': 'Upgrade Plan',
      'vip_cancel_renewal': 'Cancel Renewal',
      'vip_section_title': 'Your Subscription',
      'shield_ready': 'Auto Shield: Ready 🛡️',
      'shield_used': 'Auto Shield: Used this week 🛡️ (Resets Monday)',
      'restore_credits_label': 'Accumulated restore credits: %count% ⚡',
      'restore_vip_unlimited': 'Gold Pass Member: Unlimited Restores 👑',
      'watch_ad_btn': 'Watch Ad 🎬',
      'watch_ad_to_restore_title': 'Get Restore Credit',
      'watch_ad_to_restore_desc': 'Watch a video ad to earn 1 streak restore credit 🔥',
      'ad_reward_success': '🎬 Earned +1 Restore Credit! Total credits: %count%',
      'ad_limit_reached': '⚠️ Daily limit of 5 ads reached for streak restoration. Try again tomorrow!',
      'ad_not_finished': '⚠️ You did not watch the full ad, reward not granted!',
      'ad_load_failed': '⚠️ Failed to load ad. Please check your network connection!',
      'restore_success_toast': '🔥 Successfully restored %count% days streak! Send a Locket today to keep it active!',
      'admin_quota_tab': 'Quota & VIP 👑',
      'admin_live_events': 'LIVE EVENTS COUNTER 📊',
      // 'admin_no_users': 'No users found',
      'admin_gold_pass': 'Gold Pass: %status%',
      'admin_restore_credits': 'Restore credits: %count%',
      'admin_monthly_restore': 'Monthly restore: %status%',
      'admin_edit_streak': 'Edit Streak Credits',
      'admin_edit_streak_title': 'Streak Restore Credits',
      'admin_enter_credits': 'Enter credit amount',
      'admin_save_btn': 'Save',
      'admin_cancel_btn': 'Cancel',
      'admin_credits_updated': 'Updated restore credits for %user% to %val%',
      'admin_monthly_reset': 'Reset monthly free restores for %user%',
      'admin_gold_pass_updated': 'Updated Gold Pass status for %user%',
      'admin_users_tab_count': 'Users (%count%)',
      'admin_posts_tab': 'Posts',
      'admin_reports_tab': 'Reports',
      'admin_role_admin': 'Admin',
      'admin_role_user': 'User',
      'admin_status_used': 'Used ❌',
      'admin_status_ready': 'Ready ✅',
      'admin_cancel_gold_pass': 'Cancel Gold Pass',
      'admin_grant_gold_pass': 'Grant Gold Pass 🌟',
      'admin_reset_monthly_free_tooltip': 'Reset monthly free restores',
      'admin_event_app_open': 'Open App (app_open) 📱',
      'admin_event_login': 'Login (login) 🔑',
      'admin_event_create_post': 'Post Moment (create_post) 📸',
      'admin_event_send_message': 'Send Message (send_message) 💬',
      'admin_event_add_reaction': 'Add Reaction (add_reaction) ❤️',
      'weather_loading': 'Fetching location weather...',
      'weather_updated_toast': '🌡️ Location weather updated!',
      'tap_to_refresh_weather': 'Tap directly to refresh',
      'ad_sponsored_tooltip': 'This ad helps keep Army free for everyone. Subscribe to Army Gold Pass 🌟 to remove all ads.',
      'ad_sponsored_label': 'ⓘ Sponsored',
      'ad_loading_text': 'Loading sponsored content...',
      'ad_failed_title': 'Failed to load ad',
      'ad_failed_desc': 'Please check your connection and try again.',
      'retry_btn_label': 'Retry',
      'restore_checking_toast': 'Checking purchase history...',
      'restore_unsupported_platform': 'Restore purchases is not available on this device.',
      'restore_connect_error': 'Failed to connect to store for restore.',
      'restore_network_error': '⚠️ No network connection! Please check your Internet.',
    },
  };

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_keyLang) ?? 'vi';
    notifyListeners();
  }

  Future<void> setLanguage(String langCode) async {
    if (supportedLanguages.containsKey(langCode)) {
      _currentLanguage = langCode;
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_keyLang, langCode);
      notifyListeners();
    }
  }

  String getText(String key) {
    final value = _localizedValues[_currentLanguage]?[key] ??
        _localizedValues['vi']?[key];
    if (value == null) {
      debugPrint('[TXALanguage] ⚠️ MISSING KEY "$key" in lang "$_currentLanguage"');
      return key;
    }
    return value;
  }
}
